force-app/main/default/objects/Account/fields/Annual_Revenue_Date__c.field-meta.xml
<CustomField>
    <fullName>Annual_Revenue_Date__c</fullName>
    <label>Annual Revenue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opp_Color__mdt/Opp_Color__mdt.object-meta.xml
<CustomObject>
    <label>Opp Color</label>
    <pluralLabel>Opp Colors</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opp_Color__mdt/fields/Url_Image__c.field-meta.xml
<CustomField>
    <fullName>Url_Image__c</fullName>
    <label>Url Image</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Colour_Url__c.field-meta.xml
<CustomField>
    <fullName>Colour_Url__c</fullName>
    <label>Colour Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/OppColorCreator.cls
public class OppColorCreator {
    Opp_Color__mdt red = Opp_Color__mdt.getInstance('Red');
    Opp_Color__mdt orange = Opp_Color__mdt.getInstance('Orange');
    Opp_Color__mdt green = Opp_Color__mdt.getInstance('Green');
    Opp_Color__mdt yellow = Opp_Color__mdt.getInstance('Yellow');
    public static Opportunity createColoredOpp(Account a, Opp_Color__mdt color){
        Opportunity opp = new Opportunity(Name = a.Name+' Initial', AccountId =a.Id,
                                              CloseDate = System.today() + 3,
                                              StageName = 'Prospecting',
                                              Colour_Url__c = color.Url_Image__c);
        return opp;
    }
    public Opportunity returnedColoredOpp(Account a){
        if(a.Annual_Revenue_Date__c != System.today()) return createColoredOpp(a, orange);
        if(a.AnnualRevenue < 10000) return createColoredOpp(a, red);
        if(a.AnnualRevenue > 30000) return createColoredOpp(a, green);
        return createColoredOpp(a, yellow);
    }
}